// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCneq3GoFkR6yNAhQgAh1--k2tblj-WpT4',
    appId: '1:451079137617:web:8e09264febd59b82914b70',
    messagingSenderId: '451079137617',
    projectId: 'flutter-firebase-6f68a',
    authDomain: 'flutter-firebase-6f68a.firebaseapp.com',
    storageBucket: 'flutter-firebase-6f68a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuVkMJmPZper48_tHvpYtwT44pBDxT0Jk',
    appId: '1:451079137617:android:1ea616ab930148dd914b70',
    messagingSenderId: '451079137617',
    projectId: 'flutter-firebase-6f68a',
    storageBucket: 'flutter-firebase-6f68a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNNm9zylQpXVA2CvmCPoQEjND6v2_vMBo',
    appId: '1:451079137617:ios:221e5f5113b53534914b70',
    messagingSenderId: '451079137617',
    projectId: 'flutter-firebase-6f68a',
    storageBucket: 'flutter-firebase-6f68a.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
